[package]
name = "dashboard"
version = "0.1.0"
edition = "2021"
authors = ["<Xaytex-Development-Team>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

iced = "0.3.0"
actix-web = "0.7.19"
websocket = "0.20.2"
firebase = { git = "https://github.com/Phrohdoh/firebase-rs" }
log = "0.4.14"

[dependencies.sqlite]
version = "0.26.0"

[dependencies.serde]
version = "1.0.132"
